### Send POST request with json body
POST http://103.82.22.26:5000/api/battery/create-battery
Content-Type: application/json
Cache-Control: no-cache

{
  "idUser": 3,
  "idStation": 1,
  "rfidCode": "AAXX5U4K"
}

###
GET http://103.82.22.26:5000/api/battery/find-all-batteries
Content-Type: application/json

###
GET http://103.82.22.26:5000/api/battery/3
Content-Type: application/json

###
GET http://103.82.22.26:5000/api/battery/AAXX564H
Content-Type: application/json

###
PUT http://103.82.22.26:5000/api/battery/update-battery/6

