
PUT http://localhost:5000/api/battery/switch-pin/2
content-type: application/json
cache-control: no-cache

{
    "leftMoney": 1000000,
    "idOldPin": 1,
    "idNewPin": 2
}

###
GET http://localhost:5000/api/battery/find-user-by-rfid?code=AAXX564T
