###
GET http://127.0.0.1:5000/api/users/find-all-users HTTP/1.1
Content-Type: application/json

###
GET http://127.0.0.1:5000/api/users/3 HTTP/1.1
Accept: application/json


### Send POST request with json body
POST http://127.0.0.1:5000/api/users/create-user
Content-Type: application/json
Cache-Control: no-cache

{
  "idn": "133333384.0",
  "name": "Nguyen Thi Huy",
  "wallet": "1000000.0"
}

### UPDATE USER
PUT  http://127.0.0.1:5000/api/users/update-user/7 HTTP/1.1
content-type: application/json
cache-control: no-cache

{
  "idn": 133233061,
  "name": "Nguyen Thi Quang Huy"
}

